[package]
name = "fabric_slicing"
version = "0.1.0"
authors = ["df5602 <dominik@fankhausers.ch>"]
edition = "2018"

[dependencies]
util = { path = "../util" }
adhoc_derive = { git = "https://github.com/df5602/adhoc_derive" }
lazy_static = "1.2.0"
regex = "1.1.0"