[package]
name = "fabric_slicing"
version = "0.1.0"
authors = ["df5602 <dominik@fankhausers.ch>"]
edition = "2018"

[dependencies]
util = { path = "../util" }
adhoc_derive = "0.1.0"
lazy_static = "1.2.0"
regex = "1.1.0"