[workspace]

members = [
    "util",
    "chronal_calibration",
    "inventory_management_system",
    "fabric_slicing",
    "repose_record",
    "alchemical_reduction",
    "chronal_coordinates",
    "sum_of_its_parts",
    "memory_maneuver",
    "marble_mania",
    "stars_align",
]
